import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Sarasa Term K Nerd font"
style = "Light"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.97

[window.padding]
x = 18
y = 16
